[theme]
primaryColor="#81c784"                 # Hijau pastel (tombol, slider, aksen)
backgroundColor="#fff5f7"              # Pink pastel lembut (latar utama)
secondaryBackgroundColor="#f8ccdbff"     # Pink terang (sidebar, input)
textColor="#2c2c2c"                     # Abu gelap
background-color="#66bb6a"
font= "sans serif"
color="#5f253aff" #abu gelap

[server]
enableCORS = true
enableXsrfProtection = true