[theme]
primaryColor="#81c784"                 # Hijau pastel (tombol, slider, aksen)
backgroundColor="#f8ccdbff"              # Pink pastel lembut (latar utama)
secondaryBackgroundColor="#f8ccdbff"     # Pink terang (sidebar, input)
textColor="#2c2c2c"                     # Abu gelap
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true